// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE3RyUz3Ex_6nPXgWG48ZIw8BJ3E6_nbg',
    appId: '1:639047990515:web:a93be2e76813818aa50b86',
    messagingSenderId: '639047990515',
    projectId: 'proyecto-taller-e1ff9',
    authDomain: 'proyecto-taller-e1ff9.firebaseapp.com',
    storageBucket: 'proyecto-taller-e1ff9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC8nwZ9_qmo7FVjPx7hgYp2JmcjzPsat4',
    appId: '1:639047990515:android:55dea565c1f1adb6a50b86',
    messagingSenderId: '639047990515',
    projectId: 'proyecto-taller-e1ff9',
    storageBucket: 'proyecto-taller-e1ff9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzGrG3-0fJyPiQFe12FL7yTvwHgI_ALG4',
    appId: '1:639047990515:ios:2bfa983f292b5157a50b86',
    messagingSenderId: '639047990515',
    projectId: 'proyecto-taller-e1ff9',
    storageBucket: 'proyecto-taller-e1ff9.appspot.com',
    iosClientId: '639047990515-j14u5h29gd736kotfokfir08m51p39a9.apps.googleusercontent.com',
    iosBundleId: 'com.malenarojas.login',
  );
}
